project:
  type: website
  output-dir: docs

website:
  title: "Francesco Neri"
  favicon: files/images/favicon.ico
  search: false
  cookie-consent:
    type: express
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-Y23TGWHRGM"
    anonymize-ip: true
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume

format:
  html:
    pagetitle: "Francesco Neri"
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true

editor: visual
