project:
  type: website
  output-dir: docs

website:
  title: "Francesco Neri"
  favicon: files/images/favicon.ico
  site-url: https://f-neri.github.io/
  open-graph: true
  twitter-card: true
  search: false
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume

format:
  html:
    pagetitle: "Francesco Neri"
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
