---
title: "Resume"

format:
  html: default
  # pdf: default
---

------------------------------------------------------------------------

<i class="bi bi-geo-alt-fill"></i> San Francisco

## Summary

- PhD-trained cellular and molecular biologist with 6+ years of productive wet lab research experience. Proficient in R and comfortable with Python and shell scripting for data analysis and visualization.

- Extensive experience in primary human cell culture and building automated imaging workflows to quantitatively assess heterogeneous cellular phenotypes at the single-cell level.

- Strong communication skills and operational leadership in both academic and startup environments.

#### **Skills**

- *Cell culture*: primary human cells (fibroblasts, endothelial cells), cell lines (breast cancer, neuroblastoma)

- *Molecular biology*: qPCR, western blot, ELISA, ICC, transfection, transduction, cloning, reporter assays

- *Imaging*: high-content imaging, live-cell imaging, image analysis, method development

- *Data analysis and visualization*: R, Python, shell

## Experience

##### **Director of Research & Operations** \| NeuroAge Therapeutics \| San Francisco, CA

**Aug 2024 - Jan 2026**

- First full-time employee. Set up NeuroAge's laboratory infrastructure, including procurement of equipment, negotiating with vendors, and securing permits to ensure EH&S compliance.

- Led target validation efforts, generating preliminary data that supported the submission of grant applications. This included the development of stable knock-down lines and image-based  plate assays to quantify drug response.

- Oversaw the clinical operations of the NeuroAge Test. Responsibilities included running and maintaining the cloud-based analysis pipeline for transcriptome and whole-genome sequencing data, building a custom CRM and operations system, and managing outsourced services (sequencing companies, MRI centers, phlebotomy services).

##### **Biology of Aging PhD Student** \| Campisi Lab \| Buck Institute & University of Southern California \| Novato, CA

**Aug 2021 – Aug 2024**

- Led multiple collaborative projects with other Buck and external research groups, which resulted in 2 first-author publications on cellular senescence, an established hallmark of aging. These projects entailed developing FAST (Fully Automated Senescence Test), a high-throughput imaging method to measure senescence markers, and using high-content imaging to identify sub-populations of senescent cells with different sensitivity to senolytic treatment.

- Supported the organization and coordination of multiple international aging conferences, including managing all volunteer operations for the Seno-Therapeutic Summit 2023 and assisting with the Longevity Summit 2022, 2023, and 2024.

##### **Research Associate** \| Campisi Lab \| Buck Institute \| Novato, CA

**Oct 2019 – Aug 2021**

- Created a step-by-step workflow to generate and analyze senescent-associated secretory phenotype (SASP) samples, leading to a first-author publication. This involved collecting several protocols developed by colleagues and carefully distilling them into a generalized and clear workflow.

- Aided multiple projects led by other lab members, which resulted in 2 publications in peer-reviewed journals. My role involved preparing senescent samples using primary human cell strains.

- Performed lab managing duties, including setting up centralized laboratory resources to share tested protocols and reagents among lab members, general maintenance of lab equipment, and purchasing new instruments.

##### **Master’s Degree Intern** \| Campisi Lab \| Buck Institute \| Novato, CA

**Mar 2019 – Sep 2019**

- Contributed to characterizing the heterogeneity of the senescent-associated secretory phenotype (SASP) from cell culture senescence models, which resulted in a published manuscript in a peer-reviewed journal. Specifically, I prepared SASP samples, which involved culturing primary human cell strains, inducing cellular senescence in such cell culture models, and validating senescence induction via multiple molecular biology assays (e.g. immunocytochemistry, RT-qPCR, western blotting).

##### **Bachelor’s Degree Intern** \| Perini Lab \| University of Bologna \| Bologna, Italy

**Feb 2017 – Apr 2017**

- Established MYCN potential role in the upregulation of plasma membrane transporters SLC7A1 and SLC7A2 as measured by a luciferase assay in a MYCN-inducible neuroblastoma cell line. This involved the cloning of SLC7A1 and SLC7A2 promoter regions into a luciferase reporter plasmid, their transfection into the neuroblastoma cell line, and carrying out luciferase assays.

## Publications

```{r publication_details, echo=FALSE, eval=FALSE}

library(tidyverse)
library(rcrossref)

dois <- c("10.14336/ad.2023.0812",
          "10.1101/2023.12.22.573123",
          "10.1016/j.cmet.2021.03.008",
          "10.1002/cpz1.32",
          "10.1101/2021.02.27.433188")

publication_details <- rcrossref::cr_works(dois = dois) %>%
  .$data %>% # .$author
  mutate(
    author = map_chr(author,
                 # handle NULL values
                 ~ if(is.null(.x))
                   NA
                 else {
                   # obtain string with all author names
                   .x %>%
                     mutate(
                       full_name = str_c(given, family, sep = " ")
                     ) %>%
                     pull(full_name) %>%
                     str_c(., collapse = ", ")
                }),
    date = created,
    journal = container.title %>% str_to_title() %>%
      if_else(is.na(.), "bioRxiv", .)
  ) %>%
  select(date, journal, title, author, doi, everything()) %>%
  arrange(desc(date))

publication_details

```

- **Senescent cell heterogeneity and responses to senolytic treatment are related to cell cycle status during senescence induction**

  [Francesco Neri]{.underline}\*, Shuyuan Zheng, Mark A. Watson, Pierre-Yves Desprez, Akos A. Gerencser, Judith Campisi, Denis Wirtz, Pei-Hsun Wu, Birgit Schilling

  [Aging, 2025](https://doi.org/10.18632/aging.206299)

- **A Fully-Automated Senescence Test (FAST) for the high-throughput quantification of senescence-associated markers**

  [Francesco Neri]{.underline}, Selma N. Takajjart, Chad A. Lerner, Pierre-Yves Desprez, Birgit Schilling, Judith Campisi, Akos A. Gerencser

  [GeroScience, 2024](https://doi.org/10.1007/s11357-024-01167-3)

- **Role of the Senescence-Associated Factor Dipeptidyl Peptidase 4 in the Pathogenesis of SARS-CoV-2 Infection**

  Stefanie Deinhardt-Emmer , Sharvari Deshpande, Koji Kitazawa, Allison B. Herman, Joanna Bons, Jacob P. Rose, Prasanna Ashok Kumar, Carlos Anerillas, [Francesco Neri]{.underline}, Serban Ciotlos, Kevin Perez, Nilay Köse-Vogel, Antje Häder, Kotb Abdelmohsen, Bettina Löffler, Myriam Gorospe, Pierre-Yves Desprez, Simon Melov, David Furman, Birgit Schilling, Judith Campisi

  [Aging And Disease, 2023](http://dx.doi.org/10.14336/ad.2023.0812)

- **Oxylipin biosynthesis reinforces cellular senescence and allows detection of senolysis**

  Christopher D. Wiley, Rishi Sharma, Sonnet S. Davis, Jose Alberto Lopez-Dominguez, Kylie P. Mitchell, Samantha Wiley, Fatouma Alimirah, Dong Eun Kim, Therese Payne, Andrew Rosko, Eliezer Aimontche, Sharvari M. Deshpande, [Francesco Neri]{.underline}, Chisaka Kuehnemann, Marco Demaria, Arvind Ramanathan, Judith Campisi

  [Cell Metabolism, 2021](http://dx.doi.org/10.1016/j.cmet.2021.03.008)

- **Comprehensive Profiling of Plasma Exosomes Using Data-Independent Acquisitions – New Tools for Aging Cohort Studies**

  Sandip K. Patel, Roland Bruderer, Nathan Basisty, Joanna Bons, Pierre-Yves Desprez, [Francesco Neri]{.underline}, Lukas Reiter, Judith Campisi, Birgit Schilling

  [bioRxiv, 2021](http://dx.doi.org/10.1101/2021.02.27.433188)

- **Quantitative Proteomic Analysis of the Senescence‐Associated Secretory Phenotype by Data‐Independent Acquisition**

  [Francesco Neri]{.underline}, Nathan Basisty, Pierre‐Yves Desprez, Judith Campisi, Birgit Schilling

  [Current Protocols, 2021](http://dx.doi.org/10.1002/cpz1.32)

## Education

August 2024

**PhD in Biology of Aging** \| Buck Institute & University of Southern California \| Novato, CA

- GPA: 4.0/4.0

October 2019

**Master's degree in Pharmaceutical Biotechnology** \| University of Bologna \| Bologna, Italy

- Final mark: 110/110 *cum laude*

July 2017

**Bachelor's degree in Biotechnology** \| University of Bologna \| Bologna, Italy

- Final mark: 110/110 *cum laude*